import fs from 'node:fs/promises';
import path from 'node:path';

export type Storage = {
  write(key: string, data: Buffer): Promise<void>;
  read(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
};

// Keys are generated by us (jobs/<uuid>/<uuid>.jpg); anything else is refused
// so a crafted key can never reach outside the upload root.
const KEY_RE = /^[a-z0-9-]+(\/[a-z0-9-]+)*\.jpg$/;

export function createDiskStorage(root: string): Storage {
  const resolve = (key: string) => {
    if (!KEY_RE.test(key)) throw new Error('invalid_key');
    return path.join(root, key);
  };
  return {
    async write(key, data) {
      const file = resolve(key);
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, data, { mode: 0o600 });
    },
    read: (key) => fs.readFile(resolve(key)),
    async remove(key) {
      await fs.rm(resolve(key), { force: true });
    },
  };
}

let cached: Storage | null = null;
export function getStorage(): Storage {
  cached ??= createDiskStorage(process.env.UPLOAD_DIR || '/data/uploads');
  return cached;
}
